[system-requirements]
linux = "3.10"
libc = "2.17"

[workspace]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64"]
name = "hrd_tools"
version = "0.0.1.dev"

[pypi-dependencies]
hrd_tools = { path = ".", editable = true }

[environments]
default = { features = ["reduction"], solve-group = "default" }
xrt = { features = ["xrt", "reduction"], solve-group = "default" }
glow = { features = ["glow", "xrt"], solve-group = "default" }
docs = { features = ["docs"], solve-group = "default" }
shell = { features = ["shell"], no-default-feature = true }
lint = { features = ['lint'], no-default-feature = true }
tiled = { features = ['tiled'] }
bluesky = ["bluesky"]

[tasks]

[dependencies]
ipython = ">=9.12.0,<10"
cycler = ">=0.12.1,<0.13"
distro = ">=1.9.0,<2"
tomli-w = ">=1.2.0,<2"
python = ">=3.13.12,<3.15"
jinja2 = ">=3.1.6,<4"
ipykernel = ">=6.31.0,<8"
pyarrow = ">=22.0.0,<24"
sparse = ">=0.17.0,<0.19"
pytest = ">=9.0.2,<10"


[feature.shell.dependencies]
xonsh = ">=0.22.8,<0.23"
jedi = ">=0.19.2,<0.20"

[feature.shell.pypi-dependencies]
xontrib-jedi = ">=0.1.1, <0.2"
xontrib-vox = ">=0.0.1, <0.0.2"

[feature.glow.dependencies]
pyqt = ">=5.15.11,<6"
pyqtwebengine = ">=5.15.11,<6"
pyopengl = ">=3.1.10,<4"

[feature.docs.dependencies]
numpydoc = ">=1.10.0,<2"
sphinx-copybutton = ">=0.5.2,<0.6"
myst-parser = ">=5.0.0,<6"
sphinx = ">=9.1.0,<10"
sphinxcontrib-jquery = ">=4.1,<5"

[feature.reduction.dependencies]
h5py = ">=3.16.0,<4"
matplotlib = ">=3.10.8,<4"
pyopencl = ">=2025.2.7,<2026"
python = ">=3.14.3,<3.15"
pytools = ">=2025.2.5,<2026"
scipy = ">=1.17.1,<2"
silx = ">=2.2.2,<3"
ipykernel = ">=7.2.0,<8"
ipympl = ">=0.10.0,<0.11"
jupytext = ">=1.19.1,<2"
pandas = ">=2.3.3,<3"
tiled = ">=0.1.6,<0.2"
pymatgen = ">=2026.3.23,<2027"
scikit-image = ">=0.26.0,<0.27"

[feature.reduction.target.linux-64.dependencies]
pocl = ">=7.1,<8"

[feature.reduction.pypi-dependencies]
multianalyzer = { git = "https://github.com/kif/multianalyzer.git" }
multihead = { git = "https://github.com/tacaswell/multihead.git", rev="main"}

[feature.xrt.pypi-dependencies]
xrt = { git = "https://github.com/kklmn/xrt.git" }

[feature.xrt.dependencies]
pyopencl = ">=2025.2.7,<2026"
numpy = ">=2.4.3,<3"
pandas = ">=2.3.3,<3"
tqdm = ">=4.67.3,<5"
h5py = ">=3.16.0,<4"
pyside6 = ">=6.11.0,<7"
sparse = ">=0.18.0,<0.19"
pyarrow = ">=23.0.1,<24"

[feature.bluesky.dependencies]
bluesky = ">=1.14.6,<2"
ophyd = ">=1.11.1,<2"

[feature.lint.dependencies]
ruff = ">=0.15.8,<0.16"

[feature.lint.tasks]
check = "ruff check --fix --exclude=sims --exclude=design_scripts/CDR"
format = "ruff format --exclude=sims --exclude=design_scripts/CDR"
lint = { depends-on = ["format", "check"] }

[feature.tiled.dependencies]
tiled = ">=0.2.9,<0.3"
h5py = ">=3.16.0,<4"


[feature.tiled.tasks]
tiled_serve = { cmd = "tiled serve config config.yml --public", cwd = "tiled", env = { TILED_API_KEY = 'secret' } }
tiled_register = { cmd = "python register_helper.py /nsls2/data3/projects/next_iiia_hrd/xrt_output/", cwd = 'tiled', env = { TILED_API_KEY = 'secret' } }
